{{- if $.Values.backups.enabled }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-s3-secret
type: Opaque
data:
  AWS_ENDPOINTS: {{ $.Values.backups.backup_storage.endpoint | b64enc }}
  AWS_ACCESS_KEY_ID: {{ $.Values.backups.backup_storage.access_key | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.backups.backup_storage.secret_key | b64enc }}

{{- end }}
