{{- if $.Values.backups.enabled }}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Release.Name }}-backup
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ $.Values.backups.defaultStorageClass | quote }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataLocality: "disabled"
  numberOfReplicas: {{ $.Values.numberOfReplicas | quote }}
  staleReplicaTimeout: "30"
  fromBackup: ""
  {{- if $.Values.recurringJobSelector }}
  recurringJobSelector: 
  {{- with $.Values.recurringJobSelector }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

{{- end }}
