{{- if $.Values.backups.enabled }}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Release.Name }}-backup
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ $.Values.backups.defaultStorageClass | quote }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataLocality: "disabled"
  numberOfReplicas: {{ $.Values.numberOfReplicas | quote }}
  staleReplicaTimeout: "30"
  fromBackup: ""
  {{- if $.Values.recurringJobSelector }}
  recurringJobSelector: 
  {{- with $.Values.recurringJobSelector }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  recurringJobs: '[
    {{- if $.Values.backups.config.snapshot_enabled }}
    {
      "name":"snapshot",
      "task":"snapshot",
      "cron": "{{ $.Values.backups.config.snapshot_cron }}",
      "retain": {{ $.Values.backups.config.snapshot_retention }}
    }
    {{- end -}}
    {{- if and $.Values.backups.config.backup_enabled $.Values.backups.config.snapshot_enabled -}}
    ,
    {{ end -}}
    {{- if $.Values.backups.config.backup_enabled -}}
    {
      "name":"backup",
      "task":"backup",
      "cron": "{{ $.Values.backups.config.backup_cron }}",
      "retain": {{ $.Values.backups.config.backup_retention }}
    }
    {{- end }}
  ]'

{{- end }}
