{{- if $.Values.backups.enabled }}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Release.Name }}-backup
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
parameters:
  dataLocality: "disabled"
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs: {{ printf '[
    {
      "name":"snapshot",
      "task":"snapshot",
      "cron":"%s",
      "retain":%d
    },
    {
      "name":"backup",
      "task":"backup",
      "cron":"%s",
      "retain":%d
    }
  ]' $.Values.backups.snapshotCron $.Values.backups.snapshotRetention $.Values.backups.backupCron $.Values.backups.backupRetention }}

{{- end }}
