{{- if $.Values.backups.enabled }}

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Release.Name }}-backup
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ $.Values.backups.defaultStorageClass | quote }}
provisioner: driver.longhorn.io
parameters:
  dataLocality: "disabled"
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs: '[
    {
      "name":"snapshot",
      "task":"snapshot",
      "cron": "{{ $.Values.backups.snapshotCron }}",
      "retain": {{ $.Values.backups.snapshotRetention }}
    },
    {
      "name":"backup",
      "task":"backup",
      "cron": "{{ $.Values.backups.backupCron }}",
      "retain": {{ $.Values.backups.backupRetention }}
    }
  ]'

{{- end }}
