{{- if $.Values.backups.enabled }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-sos-secret
type: Opaque
data:
  AWS_ENDPOINTS: {{ $.Values.backups.remote_storage.enpoint | b64enc }}
  AWS_ACCESS_KEY_ID: {{ $.Values.backups.remote_storage.access_key | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.backups.remote_storage.secret_access_key | b64enc }}

{{- end }}
