# ---
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: longhorn-nfs-installation
#   labels:
#     app: longhorn-nfs-installation
#   annotations:
#     # TODO: Adapt this to work with other OSs
#     command: &cmd apt-get update -q -y && apt-get install -q -y nfs-common && modprobe nfs && apt-get install open-iscsi && modprobe iscsi_tcp && systemctl enable iscsid && systemctl start iscsid && if [ $? -eq 0 ]; then echo "nfs install successfully"; else echo "nfs install failed error code $?"; fi
# spec:
#   selector:
#     matchLabels:
#       app: longhorn-nfs-installation
#   template:
#     metadata:
#       labels:
#         app: longhorn-nfs-installation
#     spec:
#       hostNetwork: true
#       hostPID: true
#       initContainers:
#       - name: nfs-installation
#         command:
#           - nsenter
#           - --mount=/proc/1/ns/mnt
#           - --
#           - bash
#           - -c
#           - *cmd
#         image: alpine:3.12
#         securityContext:
#           privileged: true
#       containers:
#       - name: sleep
#         image: registry.k8s.io/pause:3.1
#   updateStrategy:
#     type: RollingUpdate
