{{- if $.Values.servicemonitor.enabled -}}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Release.Name }}-prometheus-servicemonitor
  labels:
    name: {{ $.Release.Name }}-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  endpoints:
  - port: manager

{{- end -}}
